application: nsshaft
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /_ah/xmpp/.*
  script: xmpp_service.py
- url: /admin/.*
  script: admin.py
  login: admin
- url: .*
  script: main.py

inbound_services:
- xmpp_message

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^simplejson/tests.*
- ^(.*/)?.*\.c$